package phd.research.enums;

/**
 * @author Jordan Doyle
 */

public enum Shape {
    BOX, POLYGON, ELLIPSE, OVAL, CIRCLE, POINT, EGG, TRIANGLE, PLAINTEXT, PLAIN, DIAMOND, TRAPEZIUM, PARALLELOGRAM,
    HOUSE, PENTAGON, HEXAGON, OCTAGON, RECT, RECTANGLE
}
